name: Test

on:
  pull_request:

jobs:
  phpcs:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
        tools: composer:v2

    - name: Install Composer dependencies
      run: composer install

    - name: Lint Coding Standards
      run: composer run phpcs

  phpstan:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: phpcs

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
        tools: composer:v2

    - name: Install Composer dependencies
      run: composer install

    - name: Static Analysis
      run: composer run phpstan