name: Automated-Testing

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["7.2", "7.3", "7.4", "8.0"]
        wordpress: ["5.7", "5.0"]
        include:
          - php: "8.0"
            wordpress: "5.7"
          - php: "8.0"
            wordpress: "5.0"
          - php: "7.4"
            wordpress: "5.7"
          - php: "7.4"
            wordpress: "5.0"
          - php: "7.3"
            wordpress: "5.7"
          - php: "7.3"
            wordpress: "5.0"
          - php: "7.2"
            wordpress: "5.7"
          - php: "7.2"
            wordpress: "5.0"
      fail-fast: false
    name: WordPress ${{ matrix.wordpress }} on PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        if: matrix.coverage == 1
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, mbstring

      - name: Get Composer Cache Directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install

      # - name: Build "testing" Docker Image
      #   env:
      #     PHP_VERSION: ${{ matrix.php }}
      #     WP_VERSION: ${{ matrix.wordpress }}
      #     USE_XDEBUG: ${{ matrix.use_xdebug }}
      #   run: composer build-test

      # - name: Run Tests w/ Docker.
      #   env:
      #     COVERAGE: ${{ matrix.coverage }}
      #     DEBUG: ${{ matrix.debug }}
      #     SKIP_TESTS_CLEANUP: ${{ matrix.coverage }}
      #     LOWEST: ${{ matrix.lowest }}
      #   run: composer run-test