name: Automated Testing

on:
  push:
    branches:
    - master
  pull_request:

env:
  COMPOSER_VERSION: "2"
  COMPOSER_CACHE: "${{ github.workspace }}/.composer-cache"

jobs:
  phpcs:
    name: PHP Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
        coverage: none
        tools: composer:v2

    - name: Install Composer Dependencies
      run: composer install

    - name: Lint Coding Standards
      run: composer run phpcs

  phpstan:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
        coverage: none
        tools: composer:v2

    - name: Install Composer Dependencies
      run: composer install

    - name: Static Analysis
      run: composer run phpstan
  
  phpunit_single_site:
    name: PHP Unit (Single Site)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start MySQL
      run: sudo systemctl start mysql.service

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - name: Setup Elasticsearch
      uses: getong/elasticsearch-action@v1.2
      with:
        elasticsearch version: '7.5.0'

    - name: Set standard 10up cache directories
      run: |
        composer config -g cache-dir "${{ env.COMPOSER_CACHE }}"
    - name: Prepare composer cache
      uses: actions/cache@v3
      with:
        path: ${{ env.COMPOSER_CACHE }}
        key: composer-${{ env.COMPOSER_VERSION }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-${{ env.COMPOSER_VERSION }}-
    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        coverage: none

    - name: Install dependencies
      run: composer install

    - name: Setup WP Tests
      run: |
        bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1
        sleep 10
    - name: PHPUnit
      run: |
        composer run-script test-single-site
  phpunit_multisite:
    name: PHP Unit (Multisite)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start MySQL
      run: sudo systemctl start mysql.service

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - name: Setup Elasticsearch
      uses: getong/elasticsearch-action@v1.2
      with:
        elasticsearch version: '7.5.0'

    - name: Set standard 10up cache directories
      run: |
        composer config -g cache-dir "${{ env.COMPOSER_CACHE }}"
    - name: Prepare composer cache
      uses: actions/cache@v3
      with:
        path: ${{ env.COMPOSER_CACHE }}
        key: composer-${{ env.COMPOSER_VERSION }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-${{ env.COMPOSER_VERSION }}-
    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        coverage: none

    - name: Install dependencies
      run: composer install

    - name: Setup WP Tests
      run: |
        bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1
        sleep 10
    - name: PHPUnit
      run: |
        composer run-script test

  cypress:
    needs: [phpcs,phpstan]
    name: ${{ matrix.core.name }} on ${{ matrix.php.name }}
    ## Pending upgrade of `@wordpress/env` package.
    continue-on-error: ${{ matrix.core.version == 'WordPress/WordPress#master' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - {name: 'PHP 8.0', version: '8.0'}
        core:
          - {name: 'WordPress Trunk', version: 'latest'}
          - {name: 'WordPress Stable', version: 'WordPress/WordPress#master'}
        include:
          - php: {name: 'PHP 7.2', version: '7.2'}
            core: {name: 'WordPress 5.7.8', version: 'WordPress/WordPress#5.7.8'}
          - php: {name: 'PHP 8.1', version: '8.1'}
            core: {name: 'WordPress Trunk', version: 'latest'}
          - php: {name: 'PHP 8.2', version: '8.2'}
            core: {name: 'WordPress Trunk', version: 'latest'}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use desired version of Node.js
      uses: actions/setup-node@v3
      with:
          node-version-file: '.nvmrc'

    - name: Check versions
      run: npm -v; node -v

    - name: Install dependencies
      run: npm install

    - name: Composer install
      run: composer install

    - name: Set the core version
      run: |
        ./tests/bin/set-core-version.js ${{ matrix.core.version }} ${{ matrix.php.version }}
        
    - name: Set up WP environment
      run: npm run env:start

    - name: Log WP environment versions
      run: |
        npx wp-env run cli "wp core version"
        npx wp-env run cli "php --version"

    - name: Test
      run: npm run cypress:run