name: Automated Testing

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  phpcs:
    name: PHP Coding Standards on PHP 8.2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none
        tools: composer:v2

    - name: Install Composer Dependencies
      run: composer install

    - name: Lint Coding Standards
      run: composer run phpcs

  phpstan:
    name: PHP Static Analysis on PHP 8.2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none
        tools: composer:v2

    - name: Install Composer Dependencies
      run: composer install

    - name: Static Analysis
      run: composer run phpstan
  
  phpunit:
    name: PHPUnit - PHP 8.2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start MySQL
      run: sudo systemctl start mysql.service

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none
        tools: composer:v2

    - name: Install dependencies
      run: composer install

    - name: Setup WP Tests
      run: bash tests/bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest
    
    - name: PHPUnit
      run: composer run phpunit

  cypress:
    needs: [phpcs,phpstan,phpunit]
    name: Cypress - PHP ${{ matrix.php.name }} with ${{ matrix.wordpress.name }}
    continue-on-error: ${{ matrix.wordpress.version == 'WordPress/WordPress#master' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - {name: '7.2', version: '7.2'}
          - {name: '8.2', version: '8.2'}
          - {name: '8.3', version: '8.3'}
        wordpress:
          - {name: 'WordPress 5.7', version: 'WordPress/WordPress#5.7.8'}
          - {name: 'WordPress Latest', version: 'latest'}
          - {name: 'WordPress Trunk', version: 'WordPress/WordPress#master'}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use desired version of Node.js
      uses: actions/setup-node@v3
      with:
          node-version-file: '.nvmrc'

    - name: Check versions
      run: npm -v; node -v

    - name: Install dependencies
      run: npm install

    - name: Composer install
      run: composer install

    - name: Set the core version
      run: |
        ./tests/bin/set-core-version.js ${{ matrix.wordpress.version }} ${{ matrix.php.version }}
        
    - name: Set up WP environment
      run: npm run env:start

    - name: Log WP environment versions
      run: |
        npx wp-env run cli "wp core version"
        npx wp-env run cli "php --version"

    - name: Test
      run: npm run cypress:run